# Generated by Django 2.0.3 on 2019-01-14 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('b_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('people', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('c_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seats', models.IntegerField(default=4)),
                ('state', models.CharField(choices=[('INA', 'Inactive'), ('RAO', 'Rest at Office'), ('LFO', 'Left from Office'), ('RAA', 'Rest at Airport'), ('LFA', 'Left from Airport')], default='INA', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('d_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dName', models.CharField(default='Nil', max_length=200)),
                ('phone', models.CharField(default='Nil', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('g_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numPassenger', models.IntegerField(default=0)),
                ('share', models.BooleanField()),
                ('travelType', models.CharField(choices=[('OA', 'Office to Airport'), ('AO', 'Airport to Office'), ('OO', 'Office to Office')], default='OA', max_length=2)),
                ('pickupTime', models.DateTimeField()),
                ('threshold', models.TimeField()),
                ('state', models.CharField(choices=[('W', 'Waiting'), ('A', 'Assigned'), ('D', 'Departed')], default='W', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('p_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pName', models.CharField(default='Nil', max_length=200)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YAPS_Server.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('p_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pName', models.CharField(default='Nil', max_length=200)),
                ('type', models.CharField(choices=[('O', 'Office'), ('A', 'Airport')], default='O', max_length=1)),
                ('inactives', models.IntegerField(default=0)),
                ('actives', models.IntegerField(default=0)),
                ('latitude', models.FloatField(default=0)),
                ('longtitude', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YAPS_Server.Driver'),
        ),
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YAPS_Server.Place'),
        ),
        migrations.AddField(
            model_name='booking',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='YAPS_Server.Car'),
        ),
        migrations.AddField(
            model_name='booking',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='YAPS_Server.Group'),
        ),
    ]
