# Generated by Django 2.0.3 on 2019-01-14 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YAPS_Server', '0002_auto_20190115_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='startLocation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='YAPS_Server.Place'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='YAPS_Server.Place'),
        ),
    ]
