# Generated by Django 2.0.3 on 2019-01-14 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YAPS_Server', '0003_auto_20190115_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='endLocation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='YAPS_Server.Place'),
            preserve_default=False,
        ),
    ]
