# Generated by Django 2.0.3 on 2019-01-14 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YAPS_Server', '0004_booking_endlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='endLocation',
        ),
        migrations.AddField(
            model_name='group',
            name='endLocation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='endLoc', to='YAPS_Server.Place'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='startLocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='startLoc', to='YAPS_Server.Place'),
        ),
    ]
