# Generated by Django 2.0.3 on 2019-01-15 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YAPS_Server', '0007_auto_20190115_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='YAPS_Server.Place'),
        ),
    ]
