# Generated by Django 2.0.3 on 2019-01-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YAPS_Server', '0008_auto_20190115_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='pickupTime',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
